Logout and endemulation
ucdavis/Harvest pull request #376
Opened 2021-07-27 22:16 UTC by jSylvestre

2021-07-27 23:13 UTC, srkirkland requested changes

2021-07-27 23:13 UTC, srkirkland commented on Harvest.Web/Startup.cs
> +            services.Configure<AuthenticationSettings>(Configuration.GetSection("Authentication"));
We should use the already existing auth settings file from a few lines up, the one that has cas login info.

2021-07-28 15:16 UTC, jSylvestre commented
Odd though... If I logout, then paste the local harvest URL in again, I get a CAS error.

2021-07-28 16:20 UTC, srkirkland approved these changes

2021-07-28 18:33 UTC, merged