Adjusted Invoice PDF to leave out empty fields
ucdavis/Harvest pull request #495
Opened 2021-09-02 18:24 UTC by wongband

resolve #488

2021-09-02 18:29 UTC, jSylvestre requested changes
I don't think this was fixed?
https://github.com/ucdavis/Harvest/blob/main/Harvest.Web/ClientApp/src/Pdf/InvoicePDF.tsx#L102
Equipment value is using labor value.

2021-09-02 18:30 UTC, wongband commented
Whoops my bad, didn't see that. I will fix it right now

2021-09-02 19:39 UTC, jSylvestre requested changes
Appears to be missing equipment?
![image](https://user-images.githubusercontent.com/469010/131905773-23c65bca-e253-4f52-b9a4-c2d041048578.png)

2021-09-02 21:45 UTC, jSylvestre approved these changes

2021-09-03 16:25 UTC, srkirkland approved these changes

2021-09-03 16:54 UTC, merged