Fixed some small issues
ucdavis/Harvest pull request #513
Opened 2021-09-07 21:18 UTC by wongband

resolve #470 
resolve #477 
resolve #483

2021-09-07 21:21 UTC, jSylvestre commented on Harvest.Web/ClientApp/src/Quotes/QuoteContainer.tsx
> +    setNotification(request, "Submitting Quote", "Quote Saved");
You need to check if it is submitting or saving.
Then change the "Saved" part as well

2021-09-07 21:24 UTC, srkirkland requested changes

2021-09-07 21:24 UTC, srkirkland commented on Harvest.Web/ClientApp/src/Quotes/QuoteContainer.tsx
> +    setNotification(request, "Submitting Quote", "Quote Saved");
This should say "Quote Submitted" when finished just for `submitted` status

2021-09-07 22:11 UTC, jSylvestre approved these changes
Didn't test, but that looks correct to me.

2021-09-08 17:20 UTC, srkirkland approved these changes

2021-09-08 17:25 UTC, merged