Added alert for project change requests
ucdavis/Harvest pull request #521
Opened 2021-09-08 23:04 UTC by wongband

resolve #482

2021-09-08 23:25 UTC, srkirkland requested changes

2021-09-08 23:25 UTC, srkirkland commented on Harvest.Web/ClientApp/src/Requests/RequestContainer.tsx
> +        <a href={`/project/details/${project.id}`} className="alert-link">
@wongband We don't ever want to use `<a>` inside a react app since that doesn't cause the client-side react-router routing.

2021-09-09 18:38 UTC, srkirkland requested changes
the already should only show up when it is actually a change request.  As it is now, it shows up during any new request.

2021-09-09 20:25 UTC, srkirkland requested changes

2021-09-09 20:25 UTC, srkirkland commented on Harvest.Web/ClientApp/src/Requests/RequestContainer.tsx
> +      {projectId && (
@wongband This works but to be consistent you should use `originalProject !== undefined` as your check

2021-09-09 20:47 UTC, jSylvestre approved these changes

2021-09-09 20:53 UTC, srkirkland approved these changes

2021-09-09 20:53 UTC, merged