Have a layout page with no react or auth stuff
ucdavis/Harvest pull request #730
Opened 2021-11-17 21:18 UTC by jSylvestre

This looks a little better (no react/menu)

![image](https://user-images.githubusercontent.com/469010/142283983-11a50645-d59b-4615-b3df-f144e14622ac.png)

2021-11-17 23:00 UTC, srkirkland commented
@jSylvestre you don't really need the layout2 page at all, just put it straight in that error page.  and then you can also leave off a bunch of those scripts as well if you want since you aren't using react or other dynamic stuff.

2021-11-17 23:07 UTC, srkirkland commented
if you do prefer a layout2 page rename it something like emptyLayout

2021-11-17 23:43 UTC, jSylvestre commented
@srkirkland  I had just copied the other layout and cut out stuff that didn't look like it was needed. I originally had it named the same, but I didn't want confusion.

But I can just dump it on the page like you had in your original suggestion.

2021-11-18 16:42 UTC, jSylvestre commented
![image](https://user-images.githubusercontent.com/469010/142458329-8f15db08-fbb4-42f1-a249-9b2ed3e76fa8.png)

2021-11-18 16:58 UTC, sprucely approved these changes
Looks good. But why the react scripts still included? Are they needed for the styles?

2021-11-18 17:00 UTC, jSylvestre commented
I didn't get the green styles without them.

2021-11-18 17:12 UTC, srkirkland requested changes

2021-11-18 17:12 UTC, srkirkland commented on Harvest.Web/Harvest.Web.csproj
> +
You don't need this -- see for example that this page references `/media/ucdavis_white_logo.svg` just fine and it's not in the csproj.  CRA will build and anything in the ClientApp/public folder will be made available at the root, nothing needed in csproj

2021-11-18 17:13 UTC, srkirkland commented
> I didn't get the green styles without them.

FWIW, only in development do you not get the green styles, in prod it'd work without the scripts.  But it doesn't really bug me too much that they are unnecessarily loaded on an error page.

2021-11-18 17:22 UTC, merged